#!/usr/bin/env python3
"""
Forensic crawler for https://ai-russia.ru/library.

Goals
-----
1. Enumerate publicly discoverable library pages without trusting the site's headline counters.
2. Separate unique URLs, unique texts, and taxonomy placements.
3. Mark cards copied from / matching the official 2024 AI Alliance casebook.
4. Grade the evidence that a card describes an implemented project rather than a potential scenario.
5. Produce a reproducible CSV/JSON/Markdown audit and duplicate/template diagnostics.

The classifier is intentionally conservative. It does NOT claim that text was generated by an LLM
and it does NOT call a page "fake". It records observable evidence and puts weak/ambiguous records
into a manual-review queue.

Example
-------
    python ai_russia_audit.py --out ai_russia_dump

Install browser once:
    playwright install chromium

See --help for discovery and rate-limit controls.
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import dataclasses
import hashlib
import json
import logging
import os
import re
import sys
import time
import urllib.parse
import urllib.robotparser
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable, Iterator, Mapping, MutableMapping, Sequence

import httpx
from bs4 import BeautifulSoup

try:
    import fitz  # PyMuPDF
except Exception:  # pragma: no cover - optional at runtime
    fitz = None  # type: ignore[assignment]

try:
    from playwright.async_api import Browser, BrowserContext, Page, async_playwright
except Exception:  # pragma: no cover - optional at runtime
    Browser = BrowserContext = Page = None  # type: ignore[assignment,misc]
    async_playwright = None  # type: ignore[assignment]

try:
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.neighbors import NearestNeighbors
except Exception:  # pragma: no cover - optional at runtime
    TfidfVectorizer = NearestNeighbors = None  # type: ignore[assignment,misc]


BASE_URL = "https://ai-russia.ru"
LIBRARY_URL = f"{BASE_URL}/library"
# The original AI Russia Works catalogue exposed year indexes outside /library/.
# They are valuable seeds for the older, actually submitted/verified case corpus; individual
# cards still resolve under /library/<slug>. Keep them as crawl indexes, not as card candidates.
LEGACY_INDEX_URLS = tuple(f"{BASE_URL}/case/{year}" for year in range(2018, 2022))
CASEBOOK_URL = (
    "https://storage.yandexcloud.net/prod-a-ai-ru-central-1-ai-russia-user-data/"
    "media/images/AI_Alliance_Casebook2024.pdf"
)
DEFAULT_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36 "
    "ai-russia-research-audit/1.0"
)

# Pages that are navigation/taxonomy rather than individual cards. The parser still validates
# every URL, so this list is only used for prioritisation and obvious exclusions.
CATEGORY_SLUG_HINTS = {
    "agriculture",
    "transport",
    "industrial",
    "industry",
    "construction",
    "finance",
    "retail",
    "telecom",
    "healthcare",
    "education",
    "government",
    "public-sector",
    "state",
}

CARD_MARKERS = (
    "какую проблему решали",
    "описание проблемы",
    "компания, внедрившая кейс",
    "внедрившая кейс",
    "бизнес-эффект",
    "результаты",
    "решение",
)

# The SPA appends recommendations, footer links and sharing controls after the last data field.
# Without an explicit stop-list those strings can be swallowed by the final parsed section and
# make an empty field look populated. Keep this intentionally conservative.
SECTION_STOP_RE = re.compile(
    r"^(?:похожие(?:\s+кейсы|\s+сценарии)?|другие(?:\s+кейсы|\s+сценарии)?|"
    r"смотрите\s+также|рекомендуем|поделиться|скопировать\s+ссылку|"
    r"все(?:\s+кейсы|\s+сценарии)?|к\s+витрине|вернуться(?:\s+назад)?|"
    r"следующий\s+кейс|предыдущий\s+кейс|о\s+проекте|контакты|"
    r"обратная\s+связь|политика\s+конфиденциальности|пользовательское\s+соглашение|"
    r"ai\s*russia|альянс\s+в\s+сфере\s+искусственного\s+интеллекта)$",
    re.IGNORECASE,
)

INLINE_ADOPTER_RE = re.compile(
    r"^(?P<name>.{2,180}?)\s*[,—–-]\s*(?:(?:компания|организация)\s*,?\s*)?"
    r"(?:внедривш(?:ая|ий|ее|ие)|реализовавш(?:ая|ий|ее|ие))\s+(?:этот\s+)?кейс[.!]?$",
    re.IGNORECASE,
)

# These patterns are not used to declare a project "fake". They prevent common catalogue
# artefacts from being mistaken for evidence of a completed deployment.
ANNOUNCEMENT_RE = re.compile(
    r"\b(?:планиру(?:ет|ется|ют)|будет\s+внедр|будут\s+внедр|внедрит|"
    r"подписал[аи]?\s+(?:соглашение|меморандум)|заключил[аи]?\s+(?:соглашение|договор)|"
    r"готовится\s+к\s+внедрению|пилотн(?:ый|ого)\s+проект|"
    r"тестиру(?:ется|ют|ет)|апробиру(?:ется|ют|ет))\b",
    re.IGNORECASE,
)
VERIFIED_BADGE_RE = re.compile(
    r"(?:AI[-‑–— ]кейсы\s+с\s+доказанной\s+бизнес[-‑–— ]эффективностью|"
    r"успешно\s+прошл[аио]?\s+проверку\s+комисси|"
    r"прош[её]л\s+экспертную\s+проверку)",
    re.IGNORECASE,
)
CONSULTANT_ONLY_RE = re.compile(
    r"(?:для\s+консультации\s+по\s+внедрению|консультация\s+по\s+внедрению|"
    r"партн[её]ры\s+по\s+внедрению)",
    re.IGNORECASE,
)
ORG_EVIDENCE_RE = re.compile(
    r"(?:\b(?:ПАО|АО|ООО|ОАО|ЗАО|ГК|ФГУП|ФГБУ|АНО|Банк|банк|"
    r"Министерство|Правительство|Администрация|Университет|Компания|компания)"
    r"\s+[«\"]?[A-ZА-ЯЁ][^\n.;:]{1,80}?[»\"]?(?=[,.;:\n]|\s+(?:внедр|запуст|интегр|автоматиз|использ|примен))|"
    r"«[^»\n]{2,80}»|"
    r"\b(?:Сбер(?:банк)?(?:ом|а|е)?|Яндекс(?:ом|а|е)?|Yandex|МТС|MTS|Т-Технологии|МегаФон|"
    r"Северсталь|Ростелеком|ЮMoney|CarMoney|NAUMEN|КСК|ЛизаАлерт|"
    r"Rocket Group|GigaChat)\b)",
    re.IGNORECASE,
)

SECTION_ALIASES: dict[str, tuple[str, ...]] = {
    "problem": (
        "какую проблему решали",
        "описание проблемы",
        "проблема",
    ),
    "solution": (
        "решение",
        "как решили",
        "описание решения",
        "принцип работы",
    ),
    "technologies": (
        "применяемые технологии",
        "используемые технологии",
        "технологии",
        "стек технологий",
    ),
    "results": (
        "результаты",
        "полученные результаты",
        "результат",
    ),
    "business_effect": (
        "бизнес-эффект",
        "бизнес эффект",
        "экономический эффект",
    ),
    "social_effect": (
        "социальный эффект",
    ),
    "image_effect": (
        "имиджевый эффект",
    ),
    "adopter": (
        "компания, внедрившая кейс",
        "компания внедрившая кейс",
        "организация, внедрившая кейс",
        "организация внедрившая кейс",
        "заказчик",
        "клиент",
        "владелец кейса",
    ),
    "developer": (
        "компания-разработчик",
        "компания разработчик",
        "разработчик",
        "поставщик решения",
    ),
    "team": (
        "команда проекта",
        "участники проекта",
    ),
    "sources": (
        "источники",
        "источник",
        "ссылки",
    ),
}

EMPTY_VALUE_PATTERNS = (
    r"^[-—–,.\s]*$",
    r"^(?:не указано|нет данных|n/?a|отсутствует|не применимо)[.\s]*$",
    r"^(?:alt|image|read more)[.\s]*$",
)

DEPLOYMENT_RE = re.compile(
    r"\b(?:внедр(?:ен|ена|ено|ены|ял(?:а|о|и)?|ил(?:а|о|и)?|яется|яются)|"
    r"запущ(?:ен|ена|ено|ены|ен в эксплуатацию)|запустил(?:а|о|и)?|"
    r"реализован(?:а|о|ы)?|реализовал(?:а|о|и)?|"
    r"интегрировал(?:а|о|и)?|автоматизировал(?:а|о|и)?|"
    r"пилот(?:ирован|ирована|ировано|ированы|ируется|ный проект)|"
    r"эксплуатиру(?:ется|ются)|введ(?:ен|ена|ено|ены) в эксплуатацию|"
    r"работает в|используется (?:в|на)|применяется (?:в|на)|"
    r"разработан(?:а|о|ы)? и (?:запущен|внедрен)|начал[аи]? работать)\b",
    re.IGNORECASE,
)
ACTUAL_RESULT_RE = re.compile(
    r"\b(?:по итогам|в результате|достиг(?:нут|нута|нуто|нуты)|"
    r"составил(?:а|о|и)?|сократил(?:ся|ась|ось|ись|и)?|"
    r"увеличил(?:ся|ась|ось|ись|и)?|повысил(?:ся|ась|ось|ись|и)?|"
    r"получен(?:а|о|ы)?|экономия составила|эффект составил|"
    r"точность составила|обработано|произведено|сэкономлено)\b",
    re.IGNORECASE,
)
POTENTIAL_RE = re.compile(
    r"\b(?:может|могут|позволит|позволяет|потенциальн\w*|"
    r"ожидаем\w*|способен|способна|способны|предполагается|"
    r"возможно|до\s+\d)\b",
    re.IGNORECASE,
)
YEAR_RE = re.compile(r"\b(?:19|20)\d{2}\b")
METRIC_RE = re.compile(
    r"(?<!\w)(?:\d{1,3}(?:[\s\u00a0]\d{3})*|\d+)(?:[.,]\d+)?\s*"
    r"(?:%|процент(?:а|ов)?|млн|млрд|тыс\.?|руб(?:лей|ля|\.)?|₽|"
    r"сек(?:унд[ыау]?|\.)?|мин(?:ут[ыау]?|\.)?|час(?:а|ов)?|дн(?:я|ей)?|"
    r"раз(?:а)?|тонн(?:ы)?|кг|шт\.?|заявок|обращений|документов|"
    r"п\.\s*п\.|x|х|×)(?!\w)",
    re.IGNORECASE,
)
TECH_RE = re.compile(
    r"\b(?:bert|rubert|roberta|gpt|llm|transformer|catboost|xgboost|"
    r"нейросет\w*|компьютерн\w+ зрени\w*|nlp|ocr|api|rag|"
    r"градиентн\w+ бустинг\w*|точност\w*|precision|recall|f1|auc|"
    r"датасет\w*|обучен\w+ выборк\w*)\b",
    re.IGNORECASE,
)
LIBRARY_PATH_RE = re.compile(
    r"(?:https?://(?:www\.)?(?:stage\.)?ai-russia\.ru)?(/library/[A-Za-zА-Яа-яЁё0-9_.~-]+)",
    re.IGNORECASE,
)

DIMENSION_KEY_RE = {
    "industry": re.compile(r"(?:^|[._-])(?:industr(?:y|ies)|sector(?:s)?|branch(?:es)?|отрасл)", re.IGNORECASE),
    "business_function": re.compile(
        r"(?:^|[._-])(?:business[_-]?function(?:s)?|biz[_-]?function(?:s)?|function(?:s)?|функци)",
        re.IGNORECASE,
    ),
    "business_task": re.compile(
        r"(?:^|[._-])(?:business[_-]?task(?:s)?|biz[_-]?task(?:s)?|task(?:s)?|задач)",
        re.IGNORECASE,
    ),
}
DIMENSION_VALUE_KEYS = ("title", "name", "label", "slug", "code", "id", "value")


@dataclasses.dataclass(slots=True)
class DiscoveryRecord:
    url: str
    sources: set[str] = dataclasses.field(default_factory=set)


@dataclasses.dataclass(slots=True)
class Card:
    url: str
    slug: str
    title: str
    visible_number: str = ""
    full_text: str = ""
    problem: str = ""
    solution: str = ""
    technologies: str = ""
    results: str = ""
    business_effect: str = ""
    social_effect: str = ""
    image_effect: str = ""
    adopter: str = ""
    developer: str = ""
    team: str = ""
    sources_text: str = ""
    tags: str = ""
    external_links: str = ""
    discovery_sources: str = ""
    industry: str = ""
    business_function: str = ""
    business_task: str = ""
    raw_html_path: str = ""
    fetch_method: str = ""
    status_code: int = 0
    content_hash: str = ""
    title_in_casebook_pdf: bool = False
    text_in_casebook_pdf: bool = False
    casebook_match_basis: str = ""
    source_family: str = "unknown"
    grade: str = "E_unclear"
    grade_score: int = 0
    grade_reasons: str = ""
    has_named_adopter: bool = False
    adopter_inferred_from_text: bool = False
    adopter_evidence_excerpt: str = ""
    has_deployment_claim: bool = False
    has_actual_result_language: bool = False
    has_metric_anywhere: bool = False
    has_metric_in_results: bool = False
    has_year: bool = False
    has_team: bool = False
    has_technical_detail: bool = False
    has_external_source: bool = False
    has_source_section: bool = False
    has_verified_badge: bool = False
    has_results_heading: bool = False
    has_business_effect_heading: bool = False
    is_announcement_only: bool = False
    consultant_or_vendor_only: bool = False
    potential_marker_count: int = 0
    empty_results: bool = True
    empty_business_effect: bool = True


class PoliteClient:
    """A tiny globally rate-limited wrapper around httpx.AsyncClient."""

    def __init__(
        self,
        *,
        timeout: float,
        delay: float,
        user_agent: str,
        verify: bool = True,
    ) -> None:
        self.delay = max(0.0, delay)
        self._last_request = 0.0
        self._lock = asyncio.Lock()
        self.client = httpx.AsyncClient(
            timeout=httpx.Timeout(timeout),
            follow_redirects=True,
            headers={
                "User-Agent": user_agent,
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,application/json;q=0.8,*/*;q=0.5",
                "Accept-Language": "ru,en;q=0.7",
            },
            verify=verify,
        )

    async def __aenter__(self) -> "PoliteClient":
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        await self.client.aclose()

    async def get(self, url: str, **kwargs: Any) -> httpx.Response:
        async with self._lock:
            elapsed = time.monotonic() - self._last_request
            if elapsed < self.delay:
                await asyncio.sleep(self.delay - elapsed)
            response = await self.client.get(url, **kwargs)
            self._last_request = time.monotonic()
            return response


class BrowserRenderer:
    def __init__(
        self,
        *,
        headless: bool,
        concurrency: int,
        user_agent: str,
        timeout_ms: int,
    ) -> None:
        self.headless = headless
        self.semaphore = asyncio.Semaphore(max(1, concurrency))
        self.user_agent = user_agent
        self.timeout_ms = timeout_ms
        self._pw: Any = None
        self._browser: Browser | None = None
        self._context: BrowserContext | None = None

    async def __aenter__(self) -> "BrowserRenderer":
        if async_playwright is None:
            raise RuntimeError(
                "Playwright is not installed. Run: pip install playwright && playwright install chromium"
            )
        self._pw = await async_playwright().start()
        self._browser = await self._pw.chromium.launch(headless=self.headless)
        self._context = await self._browser.new_context(
            user_agent=self.user_agent,
            locale="ru-RU",
            viewport={"width": 1440, "height": 1000},
        )
        self._context.set_default_timeout(self.timeout_ms)
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        if self._context is not None:
            await self._context.close()
        if self._browser is not None:
            await self._browser.close()
        if self._pw is not None:
            await self._pw.stop()

    async def render(self, url: str) -> tuple[str, int, str]:
        if self._context is None:
            raise RuntimeError("BrowserRenderer has not been entered")
        async with self.semaphore:
            page = await self._context.new_page()
            try:
                response = await page.goto(url, wait_until="domcontentloaded")
                try:
                    await page.wait_for_load_state("networkidle", timeout=min(8000, self.timeout_ms))
                except Exception:
                    pass
                await progressive_scroll(page, rounds=5)
                html = await page.content()
                status = response.status if response is not None else 0
                final_url = page.url
                return html, status, final_url
            finally:
                await page.close()


def normalize_space(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def normalize_for_match(value: str) -> str:
    value = value.lower().replace("ё", "е")
    value = value.replace("‐", "-").replace("‑", "-").replace("–", "-").replace("—", "-")
    value = re.sub(r"-\s+", "", value)  # PDF line-break hyphenation
    value = re.sub(r"[^0-9a-zа-я]+", "", value)
    return value


def normalized_text_hash(value: str) -> str:
    compact = normalize_for_match(value)
    return hashlib.sha256(compact.encode("utf-8")).hexdigest()


def canonical_url(url: str, base: str = BASE_URL) -> str:
    url = urllib.parse.urljoin(base, url)
    parsed = urllib.parse.urlsplit(url)
    host = parsed.netloc.lower()
    if host.startswith("www."):
        host = host[4:]
    if host == "stage.ai-russia.ru":
        host = "ai-russia.ru"
    path = re.sub(r"/{2,}", "/", parsed.path).rstrip("/") or "/"
    return urllib.parse.urlunsplit(("https", host, path, "", ""))


def slug_from_url(url: str) -> str:
    return urllib.parse.unquote(urllib.parse.urlsplit(url).path.rstrip("/").split("/")[-1])


def is_library_url(url: str) -> bool:
    parsed = urllib.parse.urlsplit(url)
    return parsed.netloc.lower().removeprefix("www.") in {"ai-russia.ru", "stage.ai-russia.ru"} and parsed.path.startswith(
        "/library/"
    )


def is_legacy_index_url(url: str) -> bool:
    parsed = urllib.parse.urlsplit(url)
    host_ok = parsed.netloc.lower().removeprefix("www.") in {"ai-russia.ru", "stage.ai-russia.ru"}
    return host_ok and bool(re.fullmatch(r"/case/(?:2018|2019|2020|2021)/?", parsed.path))


def looks_like_card_text(text: str, title: str = "") -> bool:
    low = text.lower()
    marker_count = sum(marker in low for marker in CARD_MARKERS)
    generic_title = title.lower().strip() in {
        "витрина ии-кейсов",
        "витрина кейсов",
        "ai russia",
        "библиотека",
    }
    return not generic_title and marker_count >= 2 and len(text) >= 160


def is_nonempty(value: str) -> bool:
    value = normalize_space(value)
    if len(value) < 2:
        return False
    return not any(re.fullmatch(pattern, value, re.IGNORECASE) for pattern in EMPTY_VALUE_PATTERNS)


def safe_filename(value: str, max_len: int = 110) -> str:
    value = re.sub(r"[^0-9A-Za-zА-Яа-яЁё._-]+", "_", value).strip("._")
    return (value[:max_len] or "item")


def add_discovery(store: MutableMapping[str, DiscoveryRecord], url: str, source: str) -> None:
    try:
        url = canonical_url(url)
    except Exception:
        return
    if not is_library_url(url):
        return
    record = store.setdefault(url, DiscoveryRecord(url=url))
    record.sources.add(source)


def iter_strings(obj: Any) -> Iterator[str]:
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, Mapping):
        for key, value in obj.items():
            yield str(key)
            yield from iter_strings(value)
    elif isinstance(obj, Sequence) and not isinstance(obj, (str, bytes, bytearray)):
        for value in obj:
            yield from iter_strings(value)


def leaf_text(value: Any, max_items: int = 20) -> str:
    values: list[str] = []
    for item in iter_strings(value):
        item = normalize_space(item)
        if item and item not in values:
            values.append(item)
        if len(values) >= max_items:
            break
    return " | ".join(values)


def flatten_keys(obj: Any, prefix: str = "", depth: int = 0, max_depth: int = 4) -> dict[str, Any]:
    out: dict[str, Any] = {}
    if depth > max_depth:
        return out
    if isinstance(obj, Mapping):
        for key, value in obj.items():
            path = f"{prefix}.{key}" if prefix else str(key)
            if isinstance(value, (str, int, float, bool)) or value is None:
                out[path.lower()] = value
            else:
                out.update(flatten_keys(value, path, depth + 1, max_depth))
    elif isinstance(obj, Sequence) and not isinstance(obj, (str, bytes, bytearray)):
        for index, value in enumerate(obj[:30]):
            out.update(flatten_keys(value, f"{prefix}[{index}]", depth + 1, max_depth))
    return out


def dimension_from_key(key: str) -> str | None:
    cleaned = re.sub(r"\[\d+\]", "", str(key).lower())
    for dimension, pattern in DIMENSION_KEY_RE.items():
        if pattern.search(cleaned):
            return dimension
    return None


def compact_dimension_value(value: Any) -> str:
    """Return a short human-readable taxonomy value, never a whole nested catalogue."""
    if isinstance(value, Mapping):
        lower = {str(key).lower(): key for key in value}
        for wanted in DIMENSION_VALUE_KEYS:
            source_key = lower.get(wanted)
            if source_key is None:
                continue
            candidate = value[source_key]
            if isinstance(candidate, (str, int, float)) and not isinstance(candidate, bool):
                text = normalize_space(candidate)
                if 0 < len(text) <= 120:
                    return text
        return ""
    if isinstance(value, (str, int, float)) and not isinstance(value, bool):
        text = normalize_space(value)
        if 0 < len(text) <= 120:
            return text
    return ""


def extract_urls_and_records_from_json(
    obj: Any,
    store: MutableMapping[str, DiscoveryRecord],
    source: str,
    records: list[dict[str, Any]],
    *,
    inherited_context: Mapping[str, str] | None = None,
    forced_dimension: str | None = None,
) -> None:
    """Recursively pull library URLs and card records from arbitrary SPA/API JSON.

    Taxonomy values are inherited down the JSON tree. This matters when an endpoint is shaped like
    `industry -> function -> task -> cards`: each card then keeps the exact matrix cell from which
    it came instead of being flattened into one lossy list of tags.
    """

    context = dict(inherited_context or {})

    if isinstance(obj, str):
        for path in LIBRARY_PATH_RE.findall(obj):
            add_discovery(store, path, source)
        return

    if isinstance(obj, Mapping):
        if forced_dimension:
            forced_value = compact_dimension_value(obj)
            if forced_value:
                context[forced_dimension] = forced_value

        # Direct scalar/mapping dimension fields on the current object. Sequences are handled item
        # by item below so one industry cannot leak into the next.
        for raw_key, value in obj.items():
            dimension = dimension_from_key(str(raw_key))
            if dimension and not isinstance(value, Sequence):
                candidate = compact_dimension_value(value)
                if candidate:
                    context[dimension] = candidate

        lower_keys = {str(k).lower(): k for k in obj.keys()}
        title_key = next((lower_keys[k] for k in ("title", "name", "heading") if k in lower_keys), None)
        slug_key = next((lower_keys[k] for k in ("slug", "code", "alias") if k in lower_keys), None)
        url_key = next((lower_keys[k] for k in ("url", "href", "link", "path") if k in lower_keys), None)

        candidate_url = ""
        if url_key is not None and isinstance(obj[url_key], str):
            candidate_url = obj[url_key]
            for path in LIBRARY_PATH_RE.findall(candidate_url):
                add_discovery(store, path, source)
        if slug_key is not None and isinstance(obj[slug_key], str):
            slug = obj[slug_key].strip()
            if re.fullmatch(r"[A-Za-zА-Яа-яЁё0-9_.~-]{2,160}", slug):
                candidate_url = f"{LIBRARY_URL}/{slug}"
                add_discovery(store, candidate_url, source)

        if title_key is not None and (slug_key is not None or candidate_url):
            flattened = flatten_keys(obj)
            flattened["_source"] = source
            flattened["_candidate_url"] = canonical_url(candidate_url) if candidate_url else ""
            for dimension, value in context.items():
                flattened[f"_context_{dimension}"] = value
            records.append(flattened)

        for raw_key, value in obj.items():
            dimension = dimension_from_key(str(raw_key))
            if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
                for child in value:
                    extract_urls_and_records_from_json(
                        child,
                        store,
                        source,
                        records,
                        inherited_context=context,
                        forced_dimension=dimension,
                    )
            else:
                extract_urls_and_records_from_json(
                    value,
                    store,
                    source,
                    records,
                    inherited_context=context,
                    forced_dimension=dimension if isinstance(value, Mapping) else None,
                )
        return

    if isinstance(obj, Sequence) and not isinstance(obj, (str, bytes, bytearray)):
        for value in obj:
            extract_urls_and_records_from_json(
                value,
                store,
                source,
                records,
                inherited_context=context,
                forced_dimension=forced_dimension,
            )


async def fetch_robots(client: PoliteClient) -> tuple[str, urllib.robotparser.RobotFileParser | None]:
    url = f"{BASE_URL}/robots.txt"
    try:
        response = await client.get(url)
        if response.status_code == 200:
            text = response.text
            parser = urllib.robotparser.RobotFileParser()
            parser.set_url(url)
            parser.parse(text.splitlines())
            return text, parser
    except Exception as exc:
        logging.debug("robots.txt unavailable: %s", exc)
    return "", None


async def discover_from_sitemaps(
    client: PoliteClient,
    store: MutableMapping[str, DiscoveryRecord],
    robots_text: str,
    raw_dir: Path,
) -> None:
    sitemap_urls = {
        f"{BASE_URL}/sitemap.xml",
        f"{BASE_URL}/sitemap_index.xml",
        f"{BASE_URL}/sitemap-index.xml",
        f"{BASE_URL}/sitemap/sitemap.xml",
    }
    for line in robots_text.splitlines():
        if line.lower().startswith("sitemap:"):
            sitemap_urls.add(line.split(":", 1)[1].strip())

    seen: set[str] = set()
    queue = list(sitemap_urls)
    while queue and len(seen) < 30:
        url = queue.pop(0)
        if url in seen:
            continue
        seen.add(url)
        try:
            response = await client.get(url)
        except Exception as exc:
            logging.debug("Sitemap failed %s: %s", url, exc)
            continue
        if response.status_code != 200 or not response.content:
            continue
        (raw_dir / f"sitemap_{len(seen):02d}.xml").write_bytes(response.content)
        try:
            root = ET.fromstring(response.content)
        except ET.ParseError:
            continue
        for loc in root.findall(".//{*}loc"):
            value = normalize_space(loc.text)
            if not value:
                continue
            if value.lower().endswith(".xml"):
                queue.append(value)
            elif is_library_url(value):
                add_discovery(store, value, "sitemap")


async def discover_from_wayback(
    client: PoliteClient,
    store: MutableMapping[str, DiscoveryRecord],
    raw_dir: Path,
) -> None:
    endpoint = "https://web.archive.org/cdx/search/cdx"
    for host in ("ai-russia.ru", "stage.ai-russia.ru"):
        params = {
            "url": f"{host}/library/*",
            "output": "json",
            "fl": "original,statuscode,mimetype,timestamp",
            "filter": "statuscode:200",
            "collapse": "urlkey",
        }
        try:
            response = await client.get(endpoint, params=params)
            if response.status_code != 200:
                continue
            data = response.json()
            (raw_dir / f"wayback_{host.replace('.', '_')}.json").write_text(
                json.dumps(data, ensure_ascii=False), encoding="utf-8"
            )
            if not isinstance(data, list) or len(data) < 2:
                continue
            header = data[0]
            try:
                original_idx = header.index("original")
            except ValueError:
                original_idx = 0
            for row in data[1:]:
                if isinstance(row, list) and len(row) > original_idx:
                    add_discovery(store, str(row[original_idx]), "wayback")
        except Exception as exc:
            logging.warning("Wayback discovery failed for %s: %s", host, exc)


async def discover_from_common_crawl(
    client: PoliteClient,
    store: MutableMapping[str, DiscoveryRecord],
    raw_dir: Path,
    indexes: int,
) -> None:
    try:
        response = await client.get("https://index.commoncrawl.org/collinfo.json")
        response.raise_for_status()
        collections = response.json()
    except Exception as exc:
        logging.warning("Common Crawl collection list failed: %s", exc)
        return

    selected = collections[: max(1, indexes)] if isinstance(collections, list) else []
    (raw_dir / "commoncrawl_collections.json").write_text(
        json.dumps(selected, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    for collection in selected:
        api = collection.get("cdx-api") if isinstance(collection, Mapping) else None
        if not api:
            continue
        for host in ("ai-russia.ru", "stage.ai-russia.ru"):
            params = {
                "url": f"{host}/library/*",
                "output": "json",
                "filter": "status:200",
                "collapse": "urlkey",
            }
            try:
                response = await client.get(str(api), params=params)
                if response.status_code != 200:
                    continue
                filename = safe_filename(f"cc_{collection.get('id','index')}_{host}") + ".jsonl"
                (raw_dir / filename).write_text(response.text, encoding="utf-8")
                for line in response.text.splitlines():
                    try:
                        row = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    url = row.get("url") if isinstance(row, Mapping) else None
                    if url:
                        add_discovery(store, str(url), f"commoncrawl:{collection.get('id','')}")
            except Exception as exc:
                logging.warning("Common Crawl query failed (%s, %s): %s", collection.get("id"), host, exc)


async def progressive_scroll(page: Page, rounds: int = 8) -> None:
    previous = -1
    stable = 0
    for _ in range(rounds):
        try:
            height = await page.evaluate("document.body.scrollHeight")
            await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            await page.wait_for_timeout(500)
        except Exception:
            return
        if height == previous:
            stable += 1
            if stable >= 2:
                break
        else:
            stable = 0
        previous = height


async def click_load_more(page: Page, max_clicks: int = 15) -> None:
    pattern = re.compile(r"(?:показать|загрузить|ещ[её]|далее|more)", re.IGNORECASE)
    for _ in range(max_clicks):
        clicked = False
        try:
            candidates = page.get_by_role("button").filter(has_text=pattern)
            count = await candidates.count()
            for index in range(min(count, 10)):
                button = candidates.nth(index)
                if await button.is_visible() and await button.is_enabled():
                    await button.click()
                    await page.wait_for_timeout(500)
                    clicked = True
                    break
        except Exception:
            pass
        if not clicked:
            break


async def discover_with_browser(
    store: MutableMapping[str, DiscoveryRecord],
    records: list[dict[str, Any]],
    raw_dir: Path,
    *,
    headless: bool,
    user_agent: str,
    timeout_ms: int,
    max_pages: int,
) -> list[dict[str, Any]]:
    if async_playwright is None:
        logging.warning("Playwright unavailable; skipping browser/network discovery")
        return []

    endpoint_rows: list[dict[str, Any]] = []
    json_tasks: set[asyncio.Task[Any]] = set()
    response_counter = 0

    async with BrowserRenderer(
        headless=headless,
        concurrency=1,
        user_agent=user_agent,
        timeout_ms=timeout_ms,
    ) as renderer:
        assert renderer._context is not None
        page = await renderer._context.new_page()

        async def handle_response(response: Any) -> None:
            nonlocal response_counter
            request = response.request
            content_type = (response.headers.get("content-type") or "").lower()
            row = {
                "url": response.url,
                "status": response.status,
                "method": request.method,
                "resource_type": request.resource_type,
                "content_type": content_type,
                "post_data": request.post_data or "",
            }
            endpoint_rows.append(row)
            if "json" not in content_type and request.resource_type not in {"xhr", "fetch"}:
                return
            try:
                data = await response.json()
            except Exception:
                return
            response_counter += 1
            json_path = raw_dir / f"network_{response_counter:04d}.json"
            try:
                json_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
            except Exception:
                pass
            before = len(records)
            extract_urls_and_records_from_json(data, store, f"network:{response.url}", records)
            for record in records[before:]:
                record["_request_url"] = response.url
                record["_request_post_data"] = request.post_data or ""
                record["_discovery_page_url"] = page.url

        def schedule_response(response: Any) -> None:
            task = asyncio.create_task(handle_response(response))
            json_tasks.add(task)
            task.add_done_callback(json_tasks.discard)

        page.on("response", schedule_response)

        queue: list[str] = [LIBRARY_URL, *LEGACY_INDEX_URLS]
        queued = set(queue)
        visited: set[str] = set()

        while queue and len(visited) < max_pages:
            url = queue.pop(0)
            if url in visited:
                continue
            visited.add(url)
            logging.info("Browser discovery %d/%d: %s", len(visited), max_pages, url)
            try:
                await page.goto(url, wait_until="domcontentloaded")
                try:
                    await page.wait_for_load_state("networkidle", timeout=min(8000, timeout_ms))
                except Exception:
                    pass
                await progressive_scroll(page)
                await click_load_more(page)
                await progressive_scroll(page, rounds=4)
            except Exception as exc:
                logging.warning("Browser discovery page failed %s: %s", url, exc)
                continue

            # Links plus their visible text help distinguish taxonomy pages from card pages.
            try:
                anchors = await page.eval_on_selector_all(
                    "a[href]",
                    "els => els.map(a => ({href: a.href, text: (a.innerText || a.textContent || '').trim()}))",
                )
            except Exception:
                anchors = []

            for anchor in anchors:
                href = anchor.get("href", "") if isinstance(anchor, Mapping) else ""
                text = normalize_space(anchor.get("text", "")) if isinstance(anchor, Mapping) else ""
                if not href:
                    continue
                canonical = canonical_url(href)
                if is_legacy_index_url(canonical):
                    if canonical not in queued and len(queued) < max_pages * 4:
                        queued.add(canonical)
                        queue.append(canonical)
                    continue
                if not is_library_url(canonical):
                    continue
                add_discovery(store, canonical, f"browser-link:{url}")
                slug = slug_from_url(canonical).lower()
                looks_taxonomy = slug in CATEGORY_SLUG_HINTS or bool(re.search(r"\d+\s+сценари", text, re.I))
                if looks_taxonomy and canonical not in queued and len(queued) < max_pages * 4:
                    queued.add(canonical)
                    queue.append(canonical)

            # Nuxt/SPA state and JSON script tags.
            try:
                states = await page.evaluate(
                    """
                    () => {
                      const out = [];
                      for (const key of ['__NUXT__','__NEXT_DATA__','__INITIAL_STATE__','__APOLLO_STATE__']) {
                        if (window[key] !== undefined) {
                          try { out.push({key, value: JSON.parse(JSON.stringify(window[key]))}); } catch (_) {}
                        }
                      }
                      for (const el of document.querySelectorAll('script[type="application/json"],script#__NEXT_DATA__')) {
                        try { out.push({key: el.id || 'script-json', value: JSON.parse(el.textContent)}); } catch (_) {}
                      }
                      return out;
                    }
                    """
                )
                for state in states or []:
                    extract_urls_and_records_from_json(state, store, f"browser-state:{url}", records)
            except Exception:
                pass

        if json_tasks:
            await asyncio.gather(*list(json_tasks), return_exceptions=True)
        await page.close()

    return endpoint_rows


def seed_catalog_urls(store: MutableMapping[str, DiscoveryRecord], maximum: int) -> None:
    for prefix in ("ml", "genai"):
        for number in range(1, maximum + 1):
            add_discovery(store, f"{LIBRARY_URL}/{prefix}{number:03d}", "catalog-seed")


def section_name(line: str) -> str | None:
    cleaned = normalize_space(line).lower().strip(" :.-—–")
    if not cleaned or len(cleaned) > 90:
        return None
    for canonical, aliases in SECTION_ALIASES.items():
        for alias in aliases:
            if cleaned == alias or cleaned.startswith(alias + ":"):
                return canonical
    return None


def parse_sections(lines: Sequence[str]) -> dict[str, str]:
    buckets: dict[str, list[str]] = defaultdict(list)
    current: str | None = None
    for raw in lines:
        line = normalize_space(raw)
        if not line:
            continue
        if SECTION_STOP_RE.fullmatch(line.strip(" :.-—–")):
            current = None
            continue
        label = section_name(line)
        if label is not None:
            current = label
            alias = next(a for a in SECTION_ALIASES[label] if line.lower().startswith(a))
            remainder = re.sub(
                r"^" + re.escape(alias),
                "",
                line,
                flags=re.IGNORECASE,
            ).strip(" :.-—–")
            if remainder:
                buckets[current].append(remainder)
            continue
        if current is not None:
            buckets[current].append(line)
    return {key: normalize_space(" ".join(values)) for key, values in buckets.items()}


def extract_inline_adopter(lines: Sequence[str]) -> str:
    """Recover cards where the UI renders `Acme, внедрившая кейс` as one line.

    Some historical pages put the company before the label, while newer pages render a normal
    label/value pair. This helper only accepts a narrow grammatical pattern to avoid guessing a
    company from ordinary prose.
    """
    for index, raw in enumerate(lines):
        line = normalize_space(raw)
        match = INLINE_ADOPTER_RE.match(line)
        if match:
            candidate = normalize_space(match.group("name")).strip(" :.-—–")
            if candidate.lower() not in {"компания", "организация", "клиент", "заказчик"} and is_nonempty(candidate):
                return candidate

        low = line.lower().strip(" :.-—–")
        if low in {"внедрившая кейс", "внедривший кейс", "реализовавшая кейс", "реализовавший кейс"} and index:
            candidate = normalize_space(lines[index - 1]).strip(" :.-—–")
            if section_name(candidate) is None and not SECTION_STOP_RE.fullmatch(candidate) and is_nonempty(candidate):
                return candidate
    return ""


def extract_title(soup: BeautifulSoup) -> str:
    for selector in ("h1", "main h2", "[itemprop='headline']"):
        node = soup.select_one(selector)
        if node:
            title = normalize_space(node.get_text(" ", strip=True))
            if title and title.lower() not in {"витрина ии-кейсов", "витрина кейсов"}:
                return re.sub(r"^\d{1,4}\s*[.)]\s*", "", title)
    for prop in (("property", "og:title"), ("name", "twitter:title")):
        node = soup.find("meta", attrs={prop[0]: prop[1]})
        if node and node.get("content"):
            title = normalize_space(node.get("content"))
            title = re.sub(r"\s+[—|-]\s+AI Russia.*$", "", title, flags=re.IGNORECASE)
            if title.lower() not in {"витрина ии-кейсов", "витрина кейсов"}:
                return title
    if soup.title:
        title = normalize_space(soup.title.get_text(" ", strip=True))
        title = re.sub(r"\s+[—|-]\s+AI Russia.*$", "", title, flags=re.IGNORECASE)
        return title
    return ""


def parse_card_html(
    html: str,
    url: str,
    *,
    discovery_sources: Iterable[str],
    status_code: int,
    fetch_method: str,
) -> Card | None:
    soup = BeautifulSoup(html, "lxml")
    for element in soup(["script", "style", "noscript", "svg"]):
        element.decompose()
    title = extract_title(soup)
    main = soup.select_one("main") or soup.body or soup
    lines = [normalize_space(value) for value in main.stripped_strings]
    lines = [line for line in lines if line]
    full_text = normalize_space(" ".join(lines))
    if not looks_like_card_text(full_text, title):
        return None

    sections = parse_sections(lines)
    if not is_nonempty(sections.get("adopter", "")):
        inline_adopter = extract_inline_adopter(lines)
        if inline_adopter:
            sections["adopter"] = inline_adopter
    visible_number = ""
    for line in lines[:40]:
        match = re.fullmatch(r"(\d{1,4})[.)]?", line)
        if match:
            visible_number = match.group(1)
            break
        match = re.match(r"^(\d{1,4})[.)]\s+", line)
        if match:
            visible_number = match.group(1)
            break

    external: list[str] = []
    tags: list[str] = []
    self_url = canonical_url(url)
    for anchor in main.select("a[href]"):
        href = urllib.parse.urljoin(url, str(anchor.get("href", "")))
        text = normalize_space(anchor.get_text(" ", strip=True))
        parsed = urllib.parse.urlsplit(href)
        host = parsed.netloc.lower().removeprefix("www.")
        if host and host not in {"ai-russia.ru", "stage.ai-russia.ru"}:
            if href not in external and not href.startswith(("mailto:", "tel:")):
                external.append(href)
        elif href and canonical_url(href) != self_url and parsed.path.startswith("/library/"):
            if text and 1 < len(text) < 80 and text not in tags:
                tags.append(text)

    return Card(
        url=self_url,
        slug=slug_from_url(self_url),
        title=title,
        visible_number=visible_number,
        full_text=full_text,
        problem=sections.get("problem", ""),
        solution=sections.get("solution", ""),
        technologies=sections.get("technologies", ""),
        results=sections.get("results", ""),
        business_effect=sections.get("business_effect", ""),
        social_effect=sections.get("social_effect", ""),
        image_effect=sections.get("image_effect", ""),
        adopter=sections.get("adopter", ""),
        developer=sections.get("developer", ""),
        team=sections.get("team", ""),
        sources_text=sections.get("sources", ""),
        tags=" | ".join(tags),
        external_links=" | ".join(external),
        discovery_sources=" | ".join(sorted(discovery_sources)),
        fetch_method=fetch_method,
        status_code=status_code,
        content_hash=normalized_text_hash(full_text),
    )


def parse_card_markdown(
    markdown: str,
    url: str,
    *,
    discovery_sources: Iterable[str],
    status_code: int,
) -> Card | None:
    lines = [normalize_space(re.sub(r"^[#>*\-\s]+", "", line)) for line in markdown.splitlines()]
    lines = [line for line in lines if line]
    title = ""
    for line in lines[:20]:
        if line.lower() not in {"витрина ии-кейсов", "витрина кейсов"} and len(line) > 3:
            title = re.sub(r"^\d{1,4}\s*[.)]\s*", "", line)
            break
    full_text = normalize_space(" ".join(lines))
    if not looks_like_card_text(full_text, title):
        return None
    sections = parse_sections(lines)
    if not is_nonempty(sections.get("adopter", "")):
        inline_adopter = extract_inline_adopter(lines)
        if inline_adopter:
            sections["adopter"] = inline_adopter
    self_url = canonical_url(url)
    return Card(
        url=self_url,
        slug=slug_from_url(self_url),
        title=title,
        full_text=full_text,
        problem=sections.get("problem", ""),
        solution=sections.get("solution", ""),
        technologies=sections.get("technologies", ""),
        results=sections.get("results", ""),
        business_effect=sections.get("business_effect", ""),
        social_effect=sections.get("social_effect", ""),
        image_effect=sections.get("image_effect", ""),
        adopter=sections.get("adopter", ""),
        developer=sections.get("developer", ""),
        team=sections.get("team", ""),
        sources_text=sections.get("sources", ""),
        discovery_sources=" | ".join(sorted(discovery_sources)),
        fetch_method="jina-reader",
        status_code=status_code,
        content_hash=normalized_text_hash(full_text),
    )


def metadata_value(record: Mapping[str, Any], patterns: Sequence[str]) -> str:
    values: list[str] = []
    for key, value in record.items():
        low = key.lower()
        if any(pattern in low for pattern in patterns):
            text = normalize_space(value)
            if text and text not in values and len(text) < 250:
                values.append(text)
    return " | ".join(values[:8])


def record_candidate_url(record: Mapping[str, Any]) -> str:
    candidate = normalize_space(record.get("_candidate_url", ""))
    if candidate:
        try:
            candidate = canonical_url(candidate)
        except Exception:
            candidate = ""
    if candidate and is_library_url(candidate):
        return candidate
    slug = metadata_value(record, (".slug", "slug", ".alias", "alias", ".code", "code"))
    slug = slug.split(" | ")[0].strip()
    if re.fullmatch(r"[A-Za-zА-Яа-яЁё0-9_.~-]{2,160}", slug):
        return canonical_url(f"{LIBRARY_URL}/{slug}")
    return ""


def record_dimension_value(record: Mapping[str, Any], dimension: str) -> str:
    """Extract one taxonomy value without swallowing an entire nested catalogue."""
    context_key = f"_context_{dimension}"
    direct = normalize_space(record.get(context_key, ""))
    if direct and len(direct) <= 180:
        return direct

    aliases: dict[str, tuple[str, ...]] = {
        "industry": ("industry", "sector", "sphere", "branch", "отрасл"),
        "business_function": (
            "business_function",
            "businessfunction",
            "biz_function",
            "function.title",
            "function.name",
            "функци",
        ),
        "business_task": (
            "business_task",
            "businesstask",
            "biz_task",
            "task.title",
            "task.name",
            "задач",
        ),
    }
    candidates: list[tuple[int, str]] = []
    for key, value in record.items():
        low = str(key).lower()
        if not any(alias in low for alias in aliases[dimension]):
            continue
        text = normalize_space(value)
        if not text or len(text) > 180 or text.startswith("http"):
            continue
        score = 0
        if low == context_key:
            score += 100
        if any(low.endswith(suffix) for suffix in (".title", ".name", ".label", ".value", ".slug")):
            score += 20
        if low.endswith(".id") or re.fullmatch(r"\d+", text):
            score -= 10
        candidates.append((score, text))
    if not candidates:
        return ""
    candidates.sort(key=lambda item: (-item[0], len(item[1]), item[1]))
    return candidates[0][1]


def merge_network_metadata(cards: list[Card], records: Sequence[Mapping[str, Any]]) -> None:
    """Attach all distinct taxonomy labels to cards, without losing multi-cell reuse."""
    by_slug: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for record in records:
        candidate_url = record_candidate_url(record)
        slug = slug_from_url(candidate_url).lower() if candidate_url else ""
        if slug:
            by_slug[slug].append(record)

    for card in cards:
        candidates = by_slug.get(card.slug.lower(), [])
        if not candidates:
            continue
        values: dict[str, set[str]] = {
            "industry": set(),
            "business_function": set(),
            "business_task": set(),
        }
        for record in candidates:
            for dimension in values:
                value = record_dimension_value(record, dimension)
                if value:
                    values[dimension].add(value)
        card.industry = " | ".join(sorted(values["industry"]))
        card.business_function = " | ".join(sorted(values["business_function"]))
        card.business_task = " | ".join(sorted(values["business_task"]))


def taxonomy_placements(
    records: Sequence[Mapping[str, Any]], cards: Sequence[Card]
) -> list[dict[str, Any]]:
    """Return unique card placements in industry × function × task cells.

    The same URL may legitimately appear in many records/endpoints. `observation_count` preserves
    that fact while the output has one row per unique placement tuple.
    """
    by_url = {card.url: card for card in cards}
    by_slug = {card.slug.lower(): card for card in cards}
    groups: dict[tuple[str, str, str, str], dict[str, Any]] = {}
    for record in records:
        url = record_candidate_url(record)
        if not url:
            continue
        card = by_url.get(url) or by_slug.get(slug_from_url(url).lower())
        industry = record_dimension_value(record, "industry")
        function = record_dimension_value(record, "business_function")
        task = record_dimension_value(record, "business_task")
        if not (industry or function or task):
            continue
        source = normalize_space(record.get("_source", "network-json")) or "network-json"
        key = (url, industry, function, task)
        row = groups.setdefault(
            key,
            {
                "url": url,
                "slug": slug_from_url(url),
                "title": card.title if card else metadata_value(record, (".title", "title", ".name", "name")),
                "grade": card.grade if card else "not_fetched",
                "source_family": card.source_family if card else "not_fetched",
                "content_hash": card.content_hash if card else "",
                "industry": industry,
                "business_function": function,
                "business_task": task,
                "observation_count": 0,
                "observation_sources": set(),
            },
        )
        row["observation_count"] += 1
        row["observation_sources"].add(source)

    output: list[dict[str, Any]] = []
    for row in groups.values():
        clean = dict(row)
        clean["observation_sources"] = " | ".join(sorted(row["observation_sources"]))
        output.append(clean)
    return sorted(
        output,
        key=lambda row: (
            str(row["industry"]),
            str(row["business_function"]),
            str(row["business_task"]),
            str(row["url"]),
        ),
    )


def matrix_counts_from_placements(
    placements: Sequence[Mapping[str, Any]], cards: Sequence[Card]
) -> list[dict[str, Any]]:
    card_by_url = {card.url: card for card in cards}
    groups: dict[tuple[str, str, str], dict[str, Any]] = {}
    for placement in placements:
        key = (
            normalize_space(placement.get("industry", "")),
            normalize_space(placement.get("business_function", "")),
            normalize_space(placement.get("business_task", "")),
        )
        row = groups.setdefault(
            key,
            {
                "urls": set(),
                "content_hashes": set(),
                "observation_count": 0,
                "grades": Counter(),
            },
        )
        url = normalize_space(placement.get("url", ""))
        if url:
            row["urls"].add(url)
        content_hash = normalize_space(placement.get("content_hash", ""))
        if content_hash:
            row["content_hashes"].add(content_hash)
        row["observation_count"] += int(placement.get("observation_count", 1) or 1)
        grade = normalize_space(placement.get("grade", ""))
        if grade:
            row["grades"][grade] += 1

    output: list[dict[str, Any]] = []
    for key, data in sorted(groups.items()):
        urls = data["urls"]
        hashes = data["content_hashes"]
        output.append(
            {
                "industry": key[0],
                "business_function": key[1],
                "business_task": key[2],
                "unique_urls": len(urls),
                "unique_texts": len(hashes) if hashes else "",
                "placement_observations": data["observation_count"],
                "grade_A": data["grades"].get("A_source_backed_implemented", 0),
                "grade_B": data["grades"].get("B_documented_implemented", 0),
                "grade_C": data["grades"].get("C_named_but_weakly_evidenced", 0),
                "grade_D": data["grades"].get("D_scenario_or_potential", 0),
                "grade_E": data["grades"].get("E_unclear", 0),
                "exactly_five_urls": len(urls) == 5,
                "exactly_five_texts": len(hashes) == 5 if hashes else "",
            }
        )
    return output


def placement_reuse_rows(placements: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for row in placements:
        url = normalize_space(row.get("url", ""))
        if url:
            grouped[url].append(row)
    output: list[dict[str, Any]] = []
    for url, rows in grouped.items():
        cells = {
            (
                normalize_space(row.get("industry", "")),
                normalize_space(row.get("business_function", "")),
                normalize_space(row.get("business_task", "")),
            )
            for row in rows
        }
        first = rows[0]
        output.append(
            {
                "url": url,
                "slug": first.get("slug", slug_from_url(url)),
                "title": first.get("title", ""),
                "grade": first.get("grade", ""),
                "source_family": first.get("source_family", ""),
                "placement_count": len(cells),
                "distinct_industries": len({cell[0] for cell in cells if cell[0]}),
                "distinct_functions": len({cell[1] for cell in cells if cell[1]}),
                "distinct_tasks": len({cell[2] for cell in cells if cell[2]}),
                "reused_across_cells": len(cells) > 1,
                "cells": " || ".join(" > ".join(part or "?" for part in cell) for cell in sorted(cells)),
            }
        )
    return sorted(output, key=lambda row: (-int(row["placement_count"]), str(row["url"])))

def extract_casebook_fingerprint(pdf_bytes: bytes) -> tuple[str, dict[str, Any]]:
    if fitz is None:
        return "", {"error": "PyMuPDF not installed"}
    document = fitz.open(stream=pdf_bytes, filetype="pdf")
    pages = [page.get_text("text") for page in document]
    text = "\n".join(pages)
    compact = normalize_space(text)
    intro = normalize_space("\n".join(pages[:4]))
    normalized = normalize_for_match(text)

    # In the designed PDF the labels and values are separate text boxes, so extraction order is
    # `решений отобрано ... 105 ... решений отобрано 100`, not necessarily `105 решений`.
    # Restrict count detection to the introduction, where both declared totals are printed.
    has_selected_label = "решений отобрано" in intro.lower()
    fingerprint = {
        "pages": document.page_count,
        "description_problem_headings": text.lower().count("описание проблемы"),
        "explicit_source_labels": len(re.findall(r"\bисточник\s*:", text, re.IGNORECASE)),
        "external_uri_annotations": sum(
            1 for page in document for link in page.get_links() if link.get("uri")
        ),
        "declared_classic_solutions": 105
        if has_selected_label and re.search(r"(?<!\d)105(?!\d)", intro)
        else None,
        "declared_genai_solutions": 100
        if has_selected_label and re.search(r"(?<!\d)100(?!\d)", intro)
        else None,
        "potential_effect_wording": bool(
            re.search(r"реальные\s*/\s*потенциально\s+достижимые\s+эффекты", compact, re.IGNORECASE)
        ),
        "sha256": hashlib.sha256(pdf_bytes).hexdigest(),
    }
    document.close()
    return normalized, fingerprint


def infer_adopter_from_deployment_text(card: Card) -> tuple[bool, str]:
    """Infer an adopter only from a sentence that also states actual operation/deployment.

    Product names in technology or consultation blocks are deliberately not enough. The exact
    triggering sentence is kept for human review.
    """
    for sentence in re.split(r"(?<=[.!?])\s+|\n+", card.full_text):
        sentence = normalize_space(sentence)
        if len(sentence) < 20 or not DEPLOYMENT_RE.search(sentence):
            continue
        organizations = [normalize_space(match.group(0)) for match in ORG_EVIDENCE_RE.finditer(sentence)]
        organizations = list(dict.fromkeys(value for value in organizations if value))
        if not organizations:
            continue
        if not card.adopter:
            card.adopter = "[inferred] " + " | ".join(organizations[:6])
        return True, sentence[:700]
    return False, ""


def classify_card(card: Card, casebook_normalized: str) -> None:
    title_norm = normalize_for_match(card.title)
    content_probe = normalize_for_match(" ".join((card.problem, card.solution)))
    card.title_in_casebook_pdf = bool(
        casebook_normalized and len(title_norm) >= 12 and title_norm in casebook_normalized
    )
    card.text_in_casebook_pdf = bool(
        casebook_normalized and len(content_probe) >= 100 and content_probe in casebook_normalized
    )
    if card.text_in_casebook_pdf:
        card.casebook_match_basis = "problem+solution exact normalized substring"
    elif card.title_in_casebook_pdf:
        card.casebook_match_basis = "title exact normalized substring"
    else:
        card.casebook_match_basis = ""

    slug_lower = card.slug.lower()
    casebook_match = card.text_in_casebook_pdf or card.title_in_casebook_pdf
    if casebook_match and re.fullmatch(r"genai\d+", slug_lower):
        card.source_family = "casebook_2024_genai"
    elif casebook_match and re.fullmatch(r"ml\d+", slug_lower):
        card.source_family = "casebook_2024_classic"
    elif casebook_match:
        card.source_family = "casebook_2024_match"
    elif re.fullmatch(r"(?:genai|ml)\d+", slug_lower):
        card.source_family = "catalog_prefix_unmatched"
    else:
        card.source_family = "legacy_or_other"

    explicit_adopter = is_nonempty(card.adopter) and len(card.adopter) >= 3
    inferred, excerpt = infer_adopter_from_deployment_text(card)
    card.adopter_inferred_from_text = inferred and not explicit_adopter
    card.adopter_evidence_excerpt = excerpt
    card.has_named_adopter = explicit_adopter or inferred

    card.has_verified_badge = bool(VERIFIED_BADGE_RE.search(card.full_text))
    card.has_deployment_claim = bool(DEPLOYMENT_RE.search(card.full_text))
    card.is_announcement_only = bool(ANNOUNCEMENT_RE.search(card.full_text)) and not card.has_deployment_claim

    results_heading_re = re.compile(r"(?:^|[\n.!?]\s*)(?:результаты|полученные результаты|результат)\s*[:]?", re.I)
    business_heading_re = re.compile(r"(?:^|[\n.!?]\s*)(?:бизнес[- ]эффект|экономический эффект)\s*[:]?", re.I)
    card.has_results_heading = bool(results_heading_re.search(card.full_text))
    card.has_business_effect_heading = bool(business_heading_re.search(card.full_text))

    result_scope = normalize_space(" ".join((card.results, card.business_effect)))
    card.has_actual_result_language = bool(ACTUAL_RESULT_RE.search(result_scope))
    card.has_metric_anywhere = bool(METRIC_RE.search(card.full_text))
    card.has_metric_in_results = bool(METRIC_RE.search(result_scope))
    card.has_year = bool(YEAR_RE.search(card.full_text))
    card.has_team = is_nonempty(card.team) and len(card.team) >= 8
    card.has_technical_detail = bool(TECH_RE.search(" ".join((card.technologies, card.solution))))
    card.has_source_section = is_nonempty(card.sources_text)
    card.has_external_source = card.has_source_section or bool(card.external_links)
    card.potential_marker_count = len(POTENTIAL_RE.findall(card.full_text))
    card.empty_results = not is_nonempty(card.results)
    card.empty_business_effect = not is_nonempty(card.business_effect)
    card.consultant_or_vendor_only = bool(
        CONSULTANT_ONLY_RE.search(card.full_text)
        and not card.has_named_adopter
        and not card.has_deployment_claim
    )

    score = 0
    reasons: list[str] = []

    if explicit_adopter:
        score += 4
        reasons.append("explicit named adopter field")
    elif inferred:
        score += 3
        reasons.append("organization named in an actual-deployment sentence")
    if card.has_deployment_claim:
        score += 3
        reasons.append("actual deployment/operation wording")
    if card.has_metric_in_results and card.has_actual_result_language:
        score += 4
        reasons.append("quantified actual result in results/effect section")
    elif card.has_metric_in_results:
        score += 1
        reasons.append("number in results/effect section, actuality unclear")
    if card.has_year:
        score += 1
        reasons.append("dated scope")
    if card.has_team:
        score += 2
        reasons.append("named project team")
    if card.has_technical_detail:
        score += 1
        reasons.append("technical detail")
    if card.has_verified_badge:
        score += 3
        reasons.append("legacy expert-verification badge/text")
    if card.has_source_section:
        score += 2
        reasons.append("explicit source section")
    elif card.external_links:
        score += 1
        reasons.append("external link present (may still be a vendor link)")

    casebook_origin = card.source_family.startswith("casebook_2024") or card.source_family == "catalog_prefix_unmatched"
    if casebook_origin and not card.has_named_adopter:
        score -= 4
        reasons.append("casebook/catalogue origin without named adopter")
    if card.is_announcement_only:
        score -= 4
        reasons.append("announcement/future pilot, not completed deployment")
    if card.potential_marker_count >= 2 and not card.has_deployment_claim:
        score -= 2
        reasons.append("mostly modal/potential wording")
    if card.empty_results and card.empty_business_effect:
        score -= 2
        reasons.append("result and business-effect sections empty/unparsed")
    if card.consultant_or_vendor_only:
        score -= 3
        reasons.append("consultants/vendors listed without adopter or operation")

    card.grade_score = score
    source_backed = card.has_source_section or card.has_verified_badge
    if (
        card.has_named_adopter
        and card.has_deployment_claim
        and card.has_metric_in_results
        and card.has_actual_result_language
        and source_backed
        and score >= 10
    ):
        card.grade = "A_source_backed_implemented"
    elif (
        (card.has_named_adopter or card.has_verified_badge)
        and card.has_deployment_claim
        and (card.has_actual_result_language or card.has_metric_in_results or card.has_team or card.has_year)
        and score >= 6
    ):
        card.grade = "B_documented_implemented"
    elif card.has_named_adopter or (card.has_verified_badge and card.has_deployment_claim):
        card.grade = "C_named_but_weakly_evidenced"
    elif casebook_origin or card.is_announcement_only or card.consultant_or_vendor_only or card.potential_marker_count >= 2:
        card.grade = "D_scenario_or_potential"
    else:
        card.grade = "E_unclear"
    card.grade_reasons = "; ".join(reasons)

def card_to_dict(card: Card) -> dict[str, Any]:
    return dataclasses.asdict(card)


def write_csv(path: Path, rows: Sequence[Mapping[str, Any]], fieldnames: Sequence[str] | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fields: list[str] = []
        for row in rows:
            for key in row.keys():
                if key not in fields:
                    fields.append(key)
        fieldnames = fields
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def sentence_openings(cards: Sequence[Card], words: int = 6) -> list[dict[str, Any]]:
    counts: Counter[str] = Counter()
    examples: dict[str, str] = {}
    for card in cards:
        for sentence in re.split(r"(?<=[.!?])\s+", card.full_text):
            tokens = re.findall(r"[A-Za-zА-Яа-яЁё0-9-]+", sentence.lower())
            if len(tokens) < words:
                continue
            opening = " ".join(tokens[:words])
            counts[opening] += 1
            examples.setdefault(opening, card.url)
    return [
        {"opening": opening, "count": count, "example_url": examples[opening]}
        for opening, count in counts.most_common()
        if count >= 3
    ]


def exact_duplicate_groups(cards: Sequence[Card]) -> list[dict[str, Any]]:
    groups: dict[str, list[Card]] = defaultdict(list)
    for card in cards:
        groups[card.content_hash].append(card)
    rows: list[dict[str, Any]] = []
    for digest, group in groups.items():
        if len(group) < 2:
            continue
        rows.append(
            {
                "content_hash": digest,
                "count": len(group),
                "titles": " | ".join(card.title for card in group),
                "urls": " | ".join(card.url for card in group),
            }
        )
    return sorted(rows, key=lambda row: int(row["count"]), reverse=True)


def near_duplicate_pairs(cards: Sequence[Card], threshold: float, neighbours: int) -> list[dict[str, Any]]:
    if TfidfVectorizer is None or NearestNeighbors is None or len(cards) < 2:
        return []
    texts = [normalize_space(" ".join((card.title, card.problem, card.solution))) for card in cards]
    vectorizer = TfidfVectorizer(
        analyzer="char_wb",
        ngram_range=(3, 5),
        min_df=2,
        max_features=120_000,
        sublinear_tf=True,
    )
    try:
        matrix = vectorizer.fit_transform(texts)
    except ValueError:
        return []
    model = NearestNeighbors(metric="cosine", algorithm="brute", n_neighbors=min(neighbours + 1, len(cards)))
    model.fit(matrix)
    distances, indices = model.kneighbors(matrix)
    seen: set[tuple[int, int]] = set()
    rows: list[dict[str, Any]] = []
    for left, (row_distances, row_indices) in enumerate(zip(distances, indices)):
        for distance, right in zip(row_distances[1:], row_indices[1:]):
            pair = tuple(sorted((left, int(right))))
            if pair in seen:
                continue
            seen.add(pair)
            similarity = 1.0 - float(distance)
            if similarity < threshold:
                continue
            rows.append(
                {
                    "similarity": round(similarity, 5),
                    "left_title": cards[pair[0]].title,
                    "left_url": cards[pair[0]].url,
                    "right_title": cards[pair[1]].title,
                    "right_url": cards[pair[1]].url,
                    "same_source_family": cards[pair[0]].source_family == cards[pair[1]].source_family,
                }
            )
    return sorted(rows, key=lambda row: float(row["similarity"]), reverse=True)


def matrix_counts_from_cards(cards: Sequence[Card]) -> list[dict[str, Any]]:
    counts: Counter[tuple[str, str, str]] = Counter()
    for card in cards:
        if card.industry or card.business_function or card.business_task:
            counts[(card.industry, card.business_function, card.business_task)] += 1
    return [
        {
            "industry": key[0],
            "business_function": key[1],
            "business_task": key[2],
            "unique_urls": count,
            "unique_texts": "",
            "placement_observations": count,
            "grade_A": "",
            "grade_B": "",
            "grade_C": "",
            "grade_D": "",
            "grade_E": "",
            "exactly_five_urls": count == 5,
            "exactly_five_texts": "",
        }
        for key, count in sorted(counts.items())
    ]


def make_verification_queries(cards: Sequence[Card]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for card in cards:
        if card.grade not in {
            "A_source_backed_implemented",
            "B_documented_implemented",
            "C_named_but_weakly_evidenced",
        }:
            continue
        adopter = card.adopter.split(" | ")[0] if card.adopter else ""
        quoted_title = f'"{card.title}"'
        query = normalize_space(f'{quoted_title} "{adopter}" внедрение искусственного интеллекта результаты')
        rows.append(
            {
                "grade": card.grade,
                "title": card.title,
                "adopter": card.adopter,
                "ai_russia_url": card.url,
                "verification_query": query,
                "external_links_on_page": card.external_links,
            }
        )
    return rows


def render_report(
    cards: Sequence[Card],
    discovery: Mapping[str, DiscoveryRecord],
    fingerprint: Mapping[str, Any],
    exact_dupes: Sequence[Mapping[str, Any]],
    near_dupes: Sequence[Mapping[str, Any]],
    matrix: Sequence[Mapping[str, Any]],
    placements: Sequence[Mapping[str, Any]],
    reuse: Sequence[Mapping[str, Any]],
) -> str:
    grades = Counter(card.grade for card in cards)
    families = Counter(card.source_family for card in cards)
    empty_results = sum(card.empty_results for card in cards)
    empty_business = sum(card.empty_business_effect for card in cards)
    empty_results_shell = sum(card.has_results_heading and card.empty_results for card in cards)
    empty_business_shell = sum(card.has_business_effect_heading and card.empty_business_effect for card in cards)
    with_adopter = sum(card.has_named_adopter for card in cards)
    casebook_matches = sum(card.title_in_casebook_pdf or card.text_in_casebook_pdf for card in cards)
    complete_cells = [
        row for row in matrix
        if row.get("industry") and row.get("business_function") and row.get("business_task")
    ]
    five_url_cells = sum(bool(row.get("exactly_five_urls")) for row in complete_cells)
    five_text_cells = sum(bool(row.get("exactly_five_texts")) for row in complete_cells)
    reused = [row for row in reuse if bool(row.get("reused_across_cells"))]
    max_reuse = max((int(row.get("placement_count", 0)) for row in reuse), default=0)
    unique_texts = len({card.content_hash for card in cards if card.content_hash})
    placement_ratio = round(len(placements) / len(cards), 3) if cards else 0

    lines = [
        "# Аудит витрины AI Russia",
        "",
        "## Что именно посчитано",
        "",
        f"- Публично обнаружено URL-кандидатов: **{len(discovery)}**.",
        f"- После загрузки и проверки структуры признано карточками: **{len(cards)}**.",
        f"- Уникальных нормализованных текстов: **{unique_texts}**.",
        f"- Уникальных размещений карточек в таксономии: **{len(placements)}**.",
        f"- Отношение размещений к URL-карточкам: **{placement_ratio}**.",
        f"- URL, замеченных более чем в одной ячейке: **{len(reused)}**; максимум размещений одного URL: **{max_reuse}**.",
        f"- Карточек, совпавших с официальным Casebook 2024 по названию или содержанию: **{casebook_matches}**.",
        f"- Карточек с конкретным внедренцем (явным либо осторожно выведенным из предложения о внедрении): **{with_adopter}**.",
        "",
        "Важно: URL, уникальный текст и размещение в матрице — разные единицы. Счётчик на сайте нельзя автоматически трактовать как число независимых проектов или внедрений.",
        "",
        "## Градация доказательности",
        "",
    ]
    for grade, count in sorted(grades.items()):
        lines.append(f"- `{grade}`: **{count}**")
    lines.extend(["", "## Происхождение карточек", ""])
    for family, count in sorted(families.items()):
        lines.append(f"- `{family}`: **{count}**")
    lines.extend(
        [
            "",
            "## Полнота доказательных полей",
            "",
            f"- Пустой/неизвлечённый раздел «Результаты»: **{empty_results}** из {len(cards)}.",
            f"- Заголовок «Результаты» есть, но содержимое пусто: **{empty_results_shell}**.",
            f"- Пустой/неизвлечённый раздел «Бизнес-эффект»: **{empty_business}** из {len(cards)}.",
            f"- Заголовок «Бизнес-эффект» есть, но содержимое пусто: **{empty_business_shell}**.",
            "",
            "## Матрица, повторное размещение и дубли",
            "",
            f"- Полных ячеек `отрасль × функция × задача`, восстановленных из network JSON: **{len(complete_cells)}**.",
            f"- Ячеек ровно с пятью уникальными URL: **{five_url_cells}**.",
            f"- Ячеек ровно с пятью уникальными текстами: **{five_text_cells}**.",
            f"- Групп полностью совпадающих нормализованных текстов: **{len(exact_dupes)}**.",
            f"- Пар с высокой символьной близостью: **{len(near_dupes)}**.",
            "",
            "Файл `taxonomy_placements.csv` показывает каждое уникальное размещение, а `placement_reuse.csv` — сколько клеток занимает один URL. Именно эти таблицы проверяют гипотезу, что большие счётчики отражают раскладку каталога, а не такое же число независимых текстов.",
            "",
            "## Отпечаток официального Casebook 2024",
            "",
        ]
    )
    for key, value in fingerprint.items():
        lines.append(f"- `{key}`: `{value}`")
    lines.extend(
        [
            "",
            "## Как читать результат",
            "",
            "- A — заявлено внедрение, в результатах есть фактическая метрика и на странице есть явный источник либо старый знак экспертной проверки.",
            "- B — документированное заявленное внедрение, но доказательная цепочка слабее класса A.",
            "- C — организация названа, однако подтверждения запуска/результата недостаточны.",
            "- D — гипотетический, каталожный, анонсированный или преимущественно потенциальный сценарий.",
            "- E — данных недостаточно либо парсер не смог однозначно разобрать страницу.",
            "",
            "A/B — это кандидаты на реальные внедрения, а не независимая истина. Для публикации окончательного списка проверьте первоисточники из `verification_queries.csv`; наличие компании на карточке само по себе внедрение не доказывает.",
            "",
            "## Ограничения",
            "",
            "- Стилометрия не доказывает авторство LLM. Отчёт измеряет происхождение из официального каталога, повторное размещение, шаблонность и силу доказательной базы.",
            "- «Все» означает все публично обнаружимые страницы через ссылки, network JSON, sitemap, Common Crawl, Wayback и предсказуемые каталожные slug. Полностью осиротевшая страница теоретически может не попасть в выборку.",
            "- Если сайт изменит DOM или схему API, число E может вырасти; сырые HTML и JSON сохраняются для повторного разбора без нового обхода.",
        ]
    )
    return "\n".join(lines) + "\n"


async def download_casebook(client: PoliteClient, out_dir: Path, enabled: bool) -> tuple[str, dict[str, Any]]:
    if not enabled:
        return "", {"disabled": True}
    pdf_path = out_dir / "sources" / "AI_Alliance_Casebook2024.pdf"
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if pdf_path.exists() and pdf_path.stat().st_size > 100_000:
            data = pdf_path.read_bytes()
        else:
            response = await client.get(CASEBOOK_URL)
            response.raise_for_status()
            data = response.content
            pdf_path.write_bytes(data)
        return extract_casebook_fingerprint(data)
    except Exception as exc:
        logging.warning("Casebook download/parse failed: %s", exc)
        return "", {"error": str(exc)}


async def fetch_one_card(
    record: DiscoveryRecord,
    client: PoliteClient,
    renderer: BrowserRenderer | None,
    raw_html_dir: Path,
    cache_dir: Path,
    *,
    use_jina: bool,
    resume: bool,
) -> Card | None:
    slug = safe_filename(slug_from_url(record.url))
    cache_path = cache_dir / f"{slug}.json"
    if resume and cache_path.exists():
        try:
            data = json.loads(cache_path.read_text(encoding="utf-8"))
            return Card(**data)
        except Exception:
            pass

    html = ""
    status = 0
    final_url = record.url
    try:
        response = await client.get(record.url)
        status = response.status_code
        final_url = str(response.url)
        content_type = (response.headers.get("content-type") or "").lower()
        if response.status_code == 200 and "html" in content_type:
            html = response.text
            card = parse_card_html(
                html,
                final_url,
                discovery_sources=record.sources,
                status_code=status,
                fetch_method="httpx",
            )
            if card is not None:
                raw_path = raw_html_dir / f"{slug}.html"
                raw_path.write_text(html, encoding="utf-8")
                card.raw_html_path = str(raw_path)
                cache_path.write_text(json.dumps(card_to_dict(card), ensure_ascii=False, indent=2), encoding="utf-8")
                return card
        if response.status_code in {404, 410}:
            return None
    except Exception as exc:
        logging.debug("Direct fetch failed %s: %s", record.url, exc)

    if renderer is not None:
        try:
            html, status, final_url = await renderer.render(record.url)
            card = parse_card_html(
                html,
                final_url,
                discovery_sources=record.sources,
                status_code=status,
                fetch_method="playwright",
            )
            if card is not None:
                raw_path = raw_html_dir / f"{slug}.html"
                raw_path.write_text(html, encoding="utf-8")
                card.raw_html_path = str(raw_path)
                cache_path.write_text(json.dumps(card_to_dict(card), ensure_ascii=False, indent=2), encoding="utf-8")
                return card
        except Exception as exc:
            logging.debug("Playwright render failed %s: %s", record.url, exc)

    if use_jina:
        reader_url = "https://r.jina.ai/" + record.url
        try:
            response = await client.get(reader_url, headers={"X-Return-Format": "markdown"})
            if response.status_code == 200:
                card = parse_card_markdown(
                    response.text,
                    record.url,
                    discovery_sources=record.sources,
                    status_code=response.status_code,
                )
                if card is not None:
                    raw_path = raw_html_dir / f"{slug}.md"
                    raw_path.write_text(response.text, encoding="utf-8")
                    card.raw_html_path = str(raw_path)
                    cache_path.write_text(
                        json.dumps(card_to_dict(card), ensure_ascii=False, indent=2), encoding="utf-8"
                    )
                    return card
        except Exception as exc:
            logging.debug("Jina Reader failed %s: %s", record.url, exc)
    return None


async def fetch_cards(
    discovery: Mapping[str, DiscoveryRecord],
    client: PoliteClient,
    renderer: BrowserRenderer | None,
    out_dir: Path,
    *,
    concurrency: int,
    max_pages: int,
    use_jina: bool,
    resume: bool,
    robots: urllib.robotparser.RobotFileParser | None,
    ignore_robots: bool,
    user_agent: str,
) -> list[Card]:
    raw_html_dir = out_dir / "raw" / "pages"
    cache_dir = out_dir / "cache" / "cards"
    raw_html_dir.mkdir(parents=True, exist_ok=True)
    cache_dir.mkdir(parents=True, exist_ok=True)

    candidates = sorted(discovery.values(), key=lambda item: item.url)
    # Root/category pages are still tested, but place likely cards first.
    candidates.sort(
        key=lambda item: (
            slug_from_url(item.url).lower() in CATEGORY_SLUG_HINTS,
            not bool(re.fullmatch(r"(?:ml|genai)\d+", slug_from_url(item.url).lower())),
            item.url,
        )
    )
    if max_pages > 0:
        candidates = candidates[:max_pages]

    semaphore = asyncio.Semaphore(max(1, concurrency))
    cards: list[Card] = []
    counter = 0
    counter_lock = asyncio.Lock()

    async def worker(item: DiscoveryRecord) -> None:
        nonlocal counter
        if robots is not None and not ignore_robots and not robots.can_fetch(user_agent, item.url):
            logging.warning("robots.txt disallows %s; skipped", item.url)
            return
        async with semaphore:
            card = await fetch_one_card(
                item,
                client,
                renderer,
                raw_html_dir,
                cache_dir,
                use_jina=use_jina,
                resume=resume,
            )
        async with counter_lock:
            counter += 1
            if counter % 25 == 0 or counter == len(candidates):
                logging.info("Fetched/validated %d/%d candidates; cards=%d", counter, len(candidates), len(cards))
        if card is not None:
            cards.append(card)

    await asyncio.gather(*(worker(item) for item in candidates))
    # Canonical URL deduplication; keep the richest parse.
    best: dict[str, Card] = {}
    for card in cards:
        previous = best.get(card.url)
        richness = len(card.full_text) + 500 * sum(
            is_nonempty(value)
            for value in (card.adopter, card.results, card.business_effect, card.team, card.technologies)
        )
        previous_richness = -1
        if previous is not None:
            previous_richness = len(previous.full_text) + 500 * sum(
                is_nonempty(value)
                for value in (
                    previous.adopter,
                    previous.results,
                    previous.business_effect,
                    previous.team,
                    previous.technologies,
                )
            )
        if previous is None or richness > previous_richness:
            best[card.url] = card
    return sorted(best.values(), key=lambda card: (card.visible_number or "999999", card.slug.lower()))


async def main_async(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).expanduser().resolve()
    (out_dir / "raw" / "discovery").mkdir(parents=True, exist_ok=True)
    logging.info("Output: %s", out_dir)

    discovery: dict[str, DiscoveryRecord] = {}
    network_records: list[dict[str, Any]] = []
    endpoint_rows: list[dict[str, Any]] = []

    # User-supplied URLs are useful when the site changes or an internal export exists.
    if args.urls_file:
        for line in Path(args.urls_file).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                add_discovery(discovery, line, "urls-file")

    async with PoliteClient(
        timeout=args.timeout,
        delay=args.delay,
        user_agent=args.user_agent,
        verify=not args.insecure,
    ) as client:
        robots_text, robots_parser = await fetch_robots(client)
        if robots_text:
            (out_dir / "raw" / "discovery" / "robots.txt").write_text(robots_text, encoding="utf-8")

        casebook_normalized, fingerprint = await download_casebook(client, out_dir, not args.no_casebook)

        if not args.no_sitemap:
            await discover_from_sitemaps(
                client,
                discovery,
                robots_text,
                out_dir / "raw" / "discovery",
            )
        if not args.no_history:
            await discover_from_common_crawl(
                client,
                discovery,
                out_dir / "raw" / "discovery",
                indexes=args.common_crawl_indexes,
            )
            await discover_from_wayback(
                client,
                discovery,
                out_dir / "raw" / "discovery",
            )
        if args.seed_max > 0:
            seed_catalog_urls(discovery, args.seed_max)

        if not args.no_browser_discovery:
            endpoint_rows = await discover_with_browser(
                discovery,
                network_records,
                out_dir / "raw" / "discovery",
                headless=not args.headful,
                user_agent=args.user_agent,
                timeout_ms=int(args.timeout * 1000),
                max_pages=args.browser_discovery_pages,
            )

        # Persist discovery before the expensive card fetch.
        discovery_rows = [
            {"url": record.url, "sources": " | ".join(sorted(record.sources))}
            for record in sorted(discovery.values(), key=lambda item: item.url)
        ]
        write_csv(out_dir / "discovery_sources.csv", discovery_rows)
        write_csv(out_dir / "network_endpoints.csv", endpoint_rows)
        with (out_dir / "network_records.jsonl").open("w", encoding="utf-8") as handle:
            for record in network_records:
                handle.write(json.dumps(record, ensure_ascii=False) + "\n")

        logging.info("Discovered %d candidate URLs", len(discovery))
        renderer_context: BrowserRenderer | None = None
        if not args.no_browser_fetch:
            try:
                renderer_context = BrowserRenderer(
                    headless=not args.headful,
                    concurrency=args.browser_concurrency,
                    user_agent=args.user_agent,
                    timeout_ms=int(args.timeout * 1000),
                )
                await renderer_context.__aenter__()
            except Exception as exc:
                logging.warning("Browser fetch disabled after startup failure: %s", exc)
                renderer_context = None

        try:
            cards = await fetch_cards(
                discovery,
                client,
                renderer_context,
                out_dir,
                concurrency=args.concurrency,
                max_pages=args.max_pages,
                use_jina=args.use_jina,
                resume=args.resume,
                robots=robots_parser,
                ignore_robots=args.ignore_robots,
                user_agent=args.user_agent,
            )
        finally:
            if renderer_context is not None:
                await renderer_context.__aexit__(None, None, None)

    merge_network_metadata(cards, network_records)
    for card in cards:
        classify_card(card, casebook_normalized)

    rows = [card_to_dict(card) for card in cards]
    write_csv(out_dir / "all_cards.csv", rows)
    with (out_dir / "all_cards.jsonl").open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")

    real = [row for row in rows if row["grade"] in {"A_source_backed_implemented", "B_documented_implemented"}]
    named = [row for row in rows if row["grade"] == "C_named_but_weakly_evidenced"]
    scenarios = [row for row in rows if row["grade"] == "D_scenario_or_potential"]
    manual = [row for row in rows if row["grade"] in {"C_named_but_weakly_evidenced", "E_unclear"}]
    write_csv(out_dir / "real_candidates.csv", real, fieldnames=list(rows[0].keys()) if rows else None)
    write_csv(out_dir / "named_weak_claims.csv", named, fieldnames=list(rows[0].keys()) if rows else None)
    write_csv(out_dir / "catalog_scenarios.csv", scenarios, fieldnames=list(rows[0].keys()) if rows else None)
    write_csv(out_dir / "manual_review.csv", manual, fieldnames=list(rows[0].keys()) if rows else None)

    exact = exact_duplicate_groups(cards)
    near = near_duplicate_pairs(cards, threshold=args.duplicate_threshold, neighbours=args.duplicate_neighbours)
    openings = sentence_openings(cards)
    placements = taxonomy_placements(network_records, cards)
    reuse = placement_reuse_rows(placements)
    matrix = (
        matrix_counts_from_placements(placements, cards)
        if placements
        else matrix_counts_from_cards(cards)
    )
    verification = make_verification_queries(cards)
    write_csv(out_dir / "exact_duplicate_groups.csv", exact)
    write_csv(out_dir / "near_duplicate_pairs.csv", near)
    write_csv(out_dir / "repeated_sentence_openings.csv", openings)
    write_csv(out_dir / "taxonomy_placements.csv", placements)
    write_csv(out_dir / "placement_reuse.csv", reuse)
    write_csv(out_dir / "matrix_counts.csv", matrix)
    write_csv(out_dir / "verification_queries.csv", verification)

    (out_dir / "casebook_fingerprint.json").write_text(
        json.dumps(fingerprint, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    report = render_report(cards, discovery, fingerprint, exact, near, matrix, placements, reuse)
    (out_dir / "report.md").write_text(report, encoding="utf-8")

    print(report)
    logging.info("Done. Main files: %s, %s", out_dir / "report.md", out_dir / "real_candidates.csv")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Enumerate and audit AI Russia library cards without treating site counters as unique cases.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--out", default="ai_russia_audit_output", help="Output directory")
    parser.add_argument("--urls-file", help="Optional newline-separated URL list to merge into discovery")
    parser.add_argument("--max-pages", type=int, default=0, help="Limit validated candidates; 0 means unlimited")
    parser.add_argument("--seed-max", type=int, default=130, help="Probe ml001..N and genai001..N")
    parser.add_argument("--browser-discovery-pages", type=int, default=24, help="Taxonomy pages visited for XHR/link discovery")
    parser.add_argument("--common-crawl-indexes", type=int, default=3, help="Newest Common Crawl indexes queried")
    parser.add_argument("--concurrency", type=int, default=3, help="Concurrent candidate workers")
    parser.add_argument("--browser-concurrency", type=int, default=2, help="Concurrent rendered card pages")
    parser.add_argument("--delay", type=float, default=0.45, help="Global delay between direct HTTP requests")
    parser.add_argument("--timeout", type=float, default=30.0, help="HTTP/browser timeout in seconds")
    parser.add_argument("--duplicate-threshold", type=float, default=0.86, help="Near-duplicate cosine threshold")
    parser.add_argument("--duplicate-neighbours", type=int, default=6, help="Nearest neighbours tested per card")
    parser.add_argument("--user-agent", default=DEFAULT_USER_AGENT)
    parser.add_argument("--headful", action="store_true", help="Show Chromium window")
    parser.add_argument("--resume", action=argparse.BooleanOptionalAction, default=True, help="Reuse per-card cache")
    parser.add_argument("--use-jina", action=argparse.BooleanOptionalAction, default=False, help="Use Jina Reader as final fallback")
    parser.add_argument("--no-sitemap", action="store_true")
    parser.add_argument("--no-history", action="store_true", help="Skip Common Crawl and Wayback URL discovery")
    parser.add_argument("--no-browser-discovery", action="store_true")
    parser.add_argument("--no-browser-fetch", action="store_true")
    parser.add_argument("--no-casebook", action="store_true")
    parser.add_argument("--ignore-robots", action="store_true", help="Ignore robots.txt (not recommended)")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS verification (not recommended)")
    parser.add_argument("--verbose", action="store_true")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )
    try:
        return asyncio.run(main_async(args))
    except KeyboardInterrupt:
        logging.warning("Interrupted; cached cards and discovery files remain reusable with --resume")
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
